# Generated by Django 4.2.16 on 2024-09-16 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0001_initial'),
        ('makeaton', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='leader_phone',
            field=models.CharField(default=9072, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teammember',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='referral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='ca.campusambassador'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='team_leader',
            field=models.BooleanField(default=False),
        ),
    ]
