# Generated by Django 4.2.16 on 2024-09-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeaton', '0002_team_leader_phone_teammember_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='applied_before',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='team_leader',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True),
        ),
    ]
