# Generated by Django 4.2.16 on 2024-09-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeaton', '0003_alter_teammember_applied_before_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='first_time_hackathon',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50, null=True),
        ),
    ]
