# Generated by Django 4.2.16 on 2024-09-17 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0001_initial'),
        ('makeaton', '0005_alter_teammember_options_teammember_diet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participants',
            fields=[
            ],
            options={
                'verbose_name': 'Participant',
                'verbose_name_plural': 'Participants',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('makeaton.teammember',),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='referral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='referrals', to='ca.campusambassador'),
        ),
    ]
