# Generated by Django 4.2.16 on 2024-09-17 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0001_initial'),
        ('makeaton', '0006_participants_alter_teammember_referral'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
            ],
            options={
                'verbose_name': 'Leaderboard',
                'verbose_name_plural': 'Leaderboards',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ca.campusambassador',),
        ),
    ]
