# Generated by Django 4.2.16 on 2024-09-17 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makeaton', '0007_leaderboard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaderboard',
            options={'verbose_name': 'Leaderboard', 'verbose_name_plural': 'Leaderboard'},
        ),
    ]
