# Generated by Django 4.2.16 on 2024-09-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeaton', '0008_alter_leaderboard_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='started_conductor',
            field=models.BooleanField(default=False),
        ),
    ]
