# Generated by Django 4.2.16 on 2024-09-18 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeaton', '0009_teammember_started_conductor'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='last_start_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
