# Generated by Django 4.2.16 on 2024-09-18 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makeaton', '0010_teammember_last_start_checked'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyTeam',
            fields=[
            ],
            options={
                'verbose_name': 'My Team',
                'verbose_name_plural': 'My Team',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('makeaton.team',),
        ),
    ]
