# Generated by Django 4.2.16 on 2024-09-21 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('makeaton', '0013_teamleader'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyTeamMember',
            fields=[
            ],
            options={
                'verbose_name': 'My Team Member',
                'verbose_name_plural': 'My Team Members',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('makeaton.teammember',),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='makeaton.team'),
        ),
    ]
