# Generated by Django 4.2.16 on 2024-09-22 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makeaton', '0016_issue_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='started_conductor',
            new_name='starred_conductor',
        ),
    ]
