# Generated by Django 4.2.16 on 2024-09-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeaton', '0017_rename_started_conductor_teammember_starred_conductor'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='leader_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
