# Generated by Django 4.2.16 on 2024-09-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeaton', '0018_teammember_leader_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='track',
            field=models.CharField(choices=[('Software', 'Software'), ('Hardware', 'Hardware')], default='Software', max_length=255),
        ),
    ]
