# Generated by Django 4.2.16 on 2024-09-28 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makeaton', '0019_team_track'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='project_details',
            new_name='why_should_select_you',
        ),
    ]
