# Generated by Django 4.2.16 on 2024-09-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeaton', '0020_rename_project_details_team_why_should_select_you'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='why_should_select_you',
            field=models.TextField(default="Describe your team, whether you are beginners or pros aiming to win big! Don't use GPT for this"),
        ),
    ]
