# Generated by Django 4.2.16 on 2024-10-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeaton', '0021_alter_team_why_should_select_you'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='level',
            field=models.CharField(blank=True, choices=[('beginner', 'beginner'), ('intermediate', 'intermediate'), ('advanced', 'advanced')], max_length=255, null=True),
        ),
    ]
