# Generated by Django 4.2.16 on 2024-10-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeaton', '0022_teammember_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='level',
            field=models.CharField(blank=True, choices=[('beginner', 'beginner'), ('intermediate', 'intermediate'), ('advanced', 'advanced')], max_length=255, null=True),
        ),
    ]
