# Generated by Django 4.2.16 on 2024-10-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeaton', '0023_team_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='llm_review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
