# Generated by Django 4.2.16 on 2024-10-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeaton', '0024_team_llm_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamLlmReview',
            fields=[
            ],
            options={
                'verbose_name': 'Team LLM Review',
                'verbose_name_plural': 'Team LLM Reviews',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('makeaton.team',),
        ),
        migrations.AddField(
            model_name='team',
            name='llm_score',
            field=models.FloatField(default=0),
        ),
    ]
