# Generated by Django 4.2.16 on 2024-10-05 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makeaton', '0025_teamllmreview_team_llm_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamRsvp',
            fields=[
            ],
            options={
                'verbose_name': 'Team RSVP',
                'verbose_name_plural': 'Team RSVPs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('makeaton.team',),
        ),
    ]
