# Generated by Django 4.2.16 on 2024-10-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeaton', '0026_teamrsvp'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='rsvp',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
    ]
