# Generated by Django 4.2.16 on 2024-10-05 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeaton', '0027_team_approved_team_rsvp'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='all_members_joined_whatsapp',
            field=models.BooleanField(default=False),
        ),
    ]
