# Generated by Django 4.2.16 on 2024-10-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeaton', '0028_team_all_members_joined_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='approved',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'Declined')], default=False),
        ),
    ]
