# Generated by Django 4.2.16 on 2024-10-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeaton', '0029_alter_team_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='id_card',
            field=models.BooleanField(default=False),
        ),
    ]
