# Generated by Django 4.2.16 on 2024-10-03 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('makeaton', '0025_teamllmreview_team_llm_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImParticipating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters')),
                ('is_generated', models.BooleanField(default=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makeaton.teammember')),
            ],
            options={
                'verbose_name': "I'm Participating Poster",
                'verbose_name_plural': "I'm Participating Posters",
            },
        ),
        migrations.CreateModel(
            name='IdCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters')),
                ('is_generated', models.BooleanField(default=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makeaton.teammember')),
            ],
            options={
                'verbose_name': 'ID Card',
                'verbose_name_plural': 'ID Cards',
            },
        ),
    ]
