# Generated by Django 4.2.16 on 2024-10-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idcard',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imparticipating',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
