# Generated by Django 4.2.16 on 2024-10-05 20:42

from django.db import migrations, models
import updates.models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0003_alter_idcard_profile_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idcard',
            name='profile_photo',
            field=models.ImageField(null=True, upload_to='profile_photos', validators=[updates.models.validate_profile_photo]),
        ),
        migrations.AlterField(
            model_name='imparticipating',
            name='profile_photo',
            field=models.ImageField(null=True, upload_to='profile_photos', validators=[updates.models.validate_profile_photo]),
        ),
    ]
