# Generated by Django 4.2.16 on 2024-10-12 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('updates', '0004_alter_idcard_profile_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('title', models.CharField(help_text='Just a title about for the post', max_length=255)),
                ('screenshot', models.ImageField(upload_to='social_media_posts')),
                ('link', models.URLField()),
                ('verified', models.BooleanField(default=False, help_text='Organizer will verify the post and mark it as verified')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
